### ISSUE TITLE
unreachable code after return statement

### ISSUE THREAD

**Issue by gdibble** [aaronmccall/rifraf#2]
via Firefox console -- warning: `unreachable code after return statement`

![image](https://cloud.githubusercontent.com/assets/906846/13235170/5afe56f0-d971-11e5-9521-3960638cce3e.png)

**Comment by gdibble** [comment]
@aaronmccall leftover `return` or some magic i'm not aware of?

**Comment by gdibble** [comment]
@aaronmccall Do you want me to remove that second `return` and issue a PR?

**Comment by aaronmccall** [comment]
@gdibble, 👍  please do.

**Comment by gdibble** [comment]
@aaronmccall Done :)
